version: '2.2'

services:
    babyfiles:
        build: service
        restart: on-failure
        ports:
            - 17101:31337
        privileged: true
        stop_grace_period: 3s
        mem_limit: 512M
        memswap_limit: 512M
        cpu_count: 1
        pids_limit: 512
        ulimits: 
            nofile:
                soft: 8192
                hard: 8192
