version: '2.4'

services:
  secure-notes:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - 17106:9000
    restart: on-failure
    pids_limit: 1024
    mem_limit: 4Gb