version: '2.4'
services:
  step1:
    build: step_1
    environment:
      - SECRET_PASSWORD=againVerYS3cr4tP44sw0rd_y0u_d0nt_gu3ss
      - SECRET_KEY=keepitSECRET_KEYSECRET_KEYSECRET_KEYSECRET_KEYkeepit
      - REDIRECT_URL=/step2forthomewhoknowtheoldschooltechniques/
    restart: on-failure
    mem_limit: 256m
    pids_limit: 1024
    networks:
      - php-challenge
  step2:
    build: step_2
    environment:
      - ANSWER=wowh0wd1dy0ug3tit?322possible
    restart: on-failure
    mem_limit: 512m
    pids_limit: 1024
    networks:
      - php-challenge
  nginx:
    image: nginx:1.18.0-alpine
    restart: on-failure
    ports:
      - "${SERVICE_PORT:-3322}:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    mem_limit: 256m
    pids_limit: 1024
    networks:
      - php-challenge

networks:
  php-challenge:
