version: '2.4'

services:
  reverse-simple-protocol:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - 17001:9000
    restart: on-failure
    pids_limit: 256
    mem_limit: 500M